name: Documentation

on:
  push:
    branches:
      - 'master'

jobs:
  Documentation:
    name: Generate and publish documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24
          rebar3-version: '3.16.1'

      - name: Generate
        run: rebar3 edoc

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
